import "./globals.css";
import localFont from "next/font/local";
import { Geist, Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});
const satoshiNormal = localFont({
  src: "../../public/fonts/Satoshi-Regular.otf",
  variable: "--font-satoshi-normal",
});

const satoshiMedium = localFont({
  src: "../../public/fonts/Satoshi-Medium.otf",
  variable: "--font-satoshi-medium",
});

 const satoshiBold = localFont({
  src: "../../public/fonts/Satoshi-Bold.otf",
  variable: "--font-satoshi-bold",
});

const sfprodisplaymedium = localFont({
  src: "../../public/fonts/Sf-Pro-Display-Medium.otf",
  variable: "--font-sfprodisplaymedium",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${satoshiMedium.variable} ${satoshiNormal.variable} ${satoshiBold.variable} ${inter.variable} ${sfprodisplaymedium.variable} ${geist.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
